"""Post add body_html

Revision ID: 212cd4517f2a
Revises: 32463802b9f1
Create Date: 2017-11-06 17:53:18.912619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212cd4517f2a'
down_revision = '32463802b9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
