"""fixbug role column upupdate

Revision ID: e14274a03169
Revises: c2df10850eb4
Create Date: 2017-11-03 15:31:31.770699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e14274a03169'
down_revision = 'c2df10850eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('roles', 'permisions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permisions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
